### PR TITLE
Split adapters

### PR DESCRIPTION
**Pull request by NiR-**
Split adapters
==========

https://php-and-symfony.matthiasnoback.nl/2014/04/theres-no-such-thing-as-an-optional-dependency/#the-solution

Why?
-------

Currently, maintaining the whole adapters suite is tough:
* from time to time, tests break on some adapters and PRs (on another adapter) just can't be merged
* there're some risks of conflicting requirements between underlying SDKs (already happened! #426)
* some adapters should be deprecated and might be replaced by something else (e.g. `Cache` adapter)

Moreover there are some architectural problems:
* Big files are not properly handled (but #334 might be a good start)
* [Metadata are not properly handled too](https://github.com/KnpLabs/Gaufrette/issues/108)
* Weird and/or duplicated behavior: `Cache` adapter & `fileRegister` in filesystem.
* Sometimes connection to external service is handled in the Adapter (e.g. [FTP](https://github.com/KnpLabs/Gaufrette/blob/master/src/Gaufrette/Adapter/Ftp.php#L499-L550)), sometimes it is not (e.g. [AwsS3](https://github.com/KnpLabs/Gaufrette/blob/master/src/Gaufrette/Adapter/AwsS3.php#L27))
* Lack of proper exceptions #395

How?
-------

Split adapters across multiple repositories, then operate needed architectural changes.

TODO:
* [ ] Deprecate adapters we don't want to support anymore
  * [ ] AmazonS3
  * [ ] Cache *(should be rewritten with PSR-16 in mind)*
* [ ] Split every adapter in its own namespace and merge it in this branch,
  * [ ] AwsS3
  * [ ] AzureBlobStorage
  * [ ] DoctrineDbal
  * [ ] Dropbox
  * [ ] Flysystem
  * [ ] Ftp
  * [ ] GoogleCloudStorage
  * [ ] GridFS
  * [ ] InMemory
  * [ ] Local
  * [ ] MogileFS
  * [ ] OpenCloud
  * [ ] PhpseclibSftp
  * [ ] Sftp
  * [ ] Zip
* [ ] Merge every possible PRs on master, release the last version on this repository, and freeze the repository,
* [ ] Merge modifications from master into this branch,
* [ ] Push the core in its new repository, update every composer.json,
* [ ] Push every adapter in its new repository
* [ ] Plans for needed architectural changes

### CODE REVIEW

**Comment by NiR-** [comment]
@flug @PedroTroller I've updated the description. What do you think?

**Comment by PedroTroller** [comment]
Do you keep the root repository with subtree system ?

**Comment by flug** [comment]
@NiR- You have a conflict with  .travis.yml

**Comment by NiR-** [comment]
@PedroTroller nope: I think the substree split would be useful only for splitting this repository the first time. After that there would be no more central repository.

@flug Yep, it's a WIP pull request/branch hence I don't really care of conflicts for now.

**Pull request closed without merging**
