### PR TITLE
Provide mime type through AwsS3 adapter

### PR DESCRIPTION
**Pull request by kcassam**
Following https://github.com/KnpLabs/Gaufrette/pull/292

---
This change is [Reviewable](https://reviewable.io/reviews/knplabs/gaufrette/362)

### CODE REVIEW

**Comment by kcassam** [comment]
I don't understand the travis error, does not seem important

**Comment by NiR-** [comment]
@kcassam Thanks for your PR. However can you update spec & functional tests please ?

**Comment by NiR-** [comment]
Any news @kcassam ?

**Comment by NiR-** [comment]
What a shame you closed it! I just realized it's still a missing feature, and it would be great to have it. I will create a new PR based on this one, with updated tests. Even so, credits will goes to you for the initial work ;)

**Pull request closed without merging**
