### PR TITLE
Add support for Google Cloud Storage

### PR DESCRIPTION
**Pull request by patkar**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #199 
| License       | MIT

### CODE REVIEW

**Comment by AronWatson** [comment]
bump

**Comment by raistlin** [comment]
@wysow Is there a chance to merge this branch?

**Comment by wysow** [comment]
@raistlin Sure it's done! ;)

@patkar Thanks for your contribution!

**Comment by patkar** [comment]
Awesome. I hope it will work without problems.

**Pull request merged**
