### PR TITLE
FIX High memory usage over time

### PR DESCRIPTION
**Pull request by robhunt3r**
FIX Memory problems when creating images from an iterator or any kind of script that constantly uses this method.

Without this fix, creating 1000 images with a 0.6mb size, ended with 700mb script in memory, but it get worse, memory size increases over time significantly.

This fix makes constant (or almost) the memory usage. Script started with 395MB in memory, 4000 iterations later it's still 395MB and images are created perfectly.

### CODE REVIEW

**Comment by NiR-** [comment]
Thanks for that PR, @robhunt3r. Dumb question for you: do you really need to keep your 1000 images in memory ?
In fact I'm not really convinced by your PR: it won't break the API but it would rather change how `File` operates, which means it would probably makes more call to remote services.

@docteurklein @akovalyov @umpirsky What do you think ?

Oh and btw, we are working on a new version of Gaufrette that will fix different high memory consumption flaws.

**Comment by umpirsky** [comment]
For me it's odd to do `$file->setContent($content)` and have `$file->content` set to `null` as a result.

**Comment by docteurklein** [comment]
as @umpirsky said, it breaks the file VO behaviour. not sure how we could do this

**Comment by umpirsky** [comment]
@robhunt3r But in your code you can do:

```php
$size = $file->setContent($content);
$file->setContent(null);
```

or override `File`.

**Comment by robhunt3r** [comment]
@NiR-  Well, I don't store 1000 images in memory, in fact I try to clean all my memory and arrays and stuff each iteration, but memory keeps increasing, it just stops when using what @umpirsky says, donig `$file->setContent(null);`, but I thought this PR would avoid doing that in our code, and let that class handle it, because until I knew where the problem comes from I spent a lot debugging, I thought it was my code.

**Comment by NiR-** [comment]
@robhunt3r Are you using any cache adapter ? Did you try to call `$filesystem->removeFromRegister($key);` ?

**Comment by robhunt3r** [comment]
Using @NiR- solution, removing from register clears the memory and everything works as spected, thank you.

Also, `$file->setcontent(null);` will end into writing 0bytes to the final file, because the `File` method, writes again to the same destination a `null` content, that's why this PR clears only memory, you can close this I think.

**Pull request closed without merging**
