### PR TITLE
add localKeys to Local adapter

### PR DESCRIPTION
**Pull request by garak**
Implement ListKeysAware for Local adapter. See also issue #250

---
This change is [Reviewable](https://reviewable.io/reviews/knplabs/gaufrette/252)

### CODE REVIEW

**Comment by wysow** [comment]
@garak if this is still relevant, can you rebase this PR?

**Comment by JoniJnm** [comment]
It's easy to use implements `ListKeysAware` in Local adapter only changing in the current `keys()` function `$this->directory` by `$this->computePath($key)`.
The problem is the function `listKeys` in [FileSystem](https://github.com/KnpLabs/Gaufrette/blob/master/src/Gaufrette/Filesystem.php#L159). I don't know why returns an array of "keys" and "directories".

It should return an array of keys. We can create maybe another function with "listDirs" or something. And the function should accept a `$recursive` function.

**Comment by stof** [comment]
We cannot change the return type of an existing method of the filesystem class. This is a BC break.

**Comment by JoniJnm** [comment]
That's way the milestone is 1.0

**Comment by NiR-** [comment]
Indeed we can't do it for 0.x. But `keys` and `listKeys` are badly design from my point of view, so eventually they'll change (for the v1).

**Comment by garak** [comment]
Being this PR too old, relevant issue closed, and hard-to-solve conflicting, I'm closing.
Thanks anyway for support

**Pull request closed without merging**
