### PR TITLE
Be more realistic

### PR DESCRIPTION
**Pull request by armetiz**
Not really needed, but it's more about philosophie ;)

### CODE REVIEW

**Comment by wysow** [comment]
@armetiz could you please fix the test suite, and thanks for this PR ;)

**Comment by armetiz** [comment]
The failed reason is not under my control.

Regards

**Comment by stof** [comment]
@wysow the failure was a network issue on Travis during the composer install. If you want it green, trigger a rebuild of this job

**Comment by wysow** [comment]
@armetiz @stof thanks guys, my bad... job restarted...

**Comment by wysow** [comment]
Thx @armetiz!

**Comment by armetiz** [comment]
Welcome ;)

**Pull request merged**
