### PR TITLE
Ensure correct return type from Flysystem adapter "exists" method

### PR DESCRIPTION
**Pull request by teohhanhui**
https://github.com/thephpleague/flysystem/blob/1.0.45/src/ReadInterface.php#L12

https://github.com/thephpleague/flysystem/blob/1.0.45/src/Filesystem.php#L57

### CODE REVIEW

**Comment by nicolasmure** [comment]
Thank you @teohhanhui !

**Comment by teohhanhui** [comment]
Will you tag a new release? :smile:

**Comment by nicolasmure** [comment]
Released in https://github.com/KnpLabs/Gaufrette/releases/tag/v0.7.0 ;)

**Comment by teohhanhui** [comment]
Thank you! =)

**Pull request merged**
