### PR TITLE
If a file we want to delete does not exist, we already deleted it successfully!

### LINKED ISSUE #318: Could not remove the "default/0001/01/70d43d74fb22538adbdc981eb6b6e3e4b318dca6.png" key.
Hi,

In my project we are using this bundle for some file uploading functionality, I dont have much knowledge about this, before it was working fine but I am facing this error. When I update new image then it works fine but when update same image with new upload again then this error come. I tried to solve it but unable to find the issue.

please help to resolve this issue.

Could not remove the "default/0001/01/70d43d74fb22538adbdc981eb6b6e3e4b318dca6.png" key.

I saw it gives exception from this file.
/vendor/knplabs/gaufrette/src/Gaufrette/Filesystem.php

```
/**
 * Deletes the file matching the specified key
 *
 * @param string $key
 * @throws \RuntimeException when cannot read file
 *
 * @return boolean
 */
public function delete($key)
{
    $this->assertHasFile($key);

    if ($this->adapter->delete($key)) {
        return true;
    }

    throw new \RuntimeException(sprintf('Could not remove the "%s" key.', $key));
}
```

snapshot332

### PR DESCRIPTION
**Pull request by lemoinem**
Fixes #318

### CODE REVIEW

**Comment by lemoinem** [comment]
Travis with PHP 5.4 fails because the php-ext2 extension is not available.
This is not related to my changes.

**Comment by NiR-** [comment]
@lemoinem I am not really confident with your PR: any filesystem would complain if you try to delete a file that does not exists rather than silently failing. I think we should keep the same behavior for our filesystem abstraction layer.

**Comment by akovalyov** [comment]
I completely agree with @NiR-. If file was not found - it is unexpected behaviour. I.e., `rm` will through you `rm: cannot remove ‘my.file’: No such file or directory`. 
If such a behavior is expected - then the exception thrown by Gaufrette should be caught in your code.

Another question is that `\RuntimeException` is thrown there. It should be changed to `Gaufrette\Exception\FileNotFound`.

**Comment by lemoinem** [comment]
OK, Thanks for the feedback...

**Pull request closed without merging**
