### PR TITLE
Timeout Option for FTP Configuration

### PR DESCRIPTION
**Pull request by KonstantinCodes**
FTP Timeouts caused our Nginx to produce `504 Gateway Time-out` Errors.
Here you can set a timeout configuration that plays nice with your individual setup.
In Collaboration with @cmyker

### CODE REVIEW

**Comment by mvhirsch** [comment]
I would love to see this feature soon too! So I want to offer help.

@flug I just checked the failed builds, but it's about parsing error in Doctrine's Collection class. This doesn't look like an issue by @KonstantinCodes' changes, does it? Can you please take a look?

**Comment by flug** [comment]
Hum maybe we need to change the version of doctrine/dbal. 
@NiR- an idea or it's good ?

**Comment by mvhirsch** [comment]
@flug @NiR- any news so far?

**Comment by mvhirsch** [comment]
Thank you @NiR-

**Pull request merged**
